# ddclient.conf file from https://github.com/ddclient/ddclient/blob/main/ddclient.conf.in

daemon=600                              # check every 600 seconds
syslog=yes                              # log update msgs to syslog
pid=/var/run/ddclient/ddclient.pid      # record PID in file.
ssl=yes                                 # use ssl-support.

use=web, web=https://ipinfo.io/ip

protocol=cloudflare
ttl=1
login_env=CLOUDFLARE_LOGIN_EMAIL
password_env=CLOUDFLARE_LOGIN_PW
zone_env=CLOUDFLARE_DOMAIN
env_var=CLOUDFLARE_DOMAIN